---
- name: restart docker daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  listen: restart docker daemon

- name: restart mailpit
  ansible.builtin.command:
    cmd: docker compose restart mailpit
    chdir: "{{ mail_relay_compose_dir }}"
  listen: restart mailpit
