---
- name: restart gophish
  ansible.builtin.command:
    cmd: docker compose restart gophish
    chdir: "{{ phishing_simulator_compose_dir }}"
  listen: restart gophish

- name: restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
