---
collections:
  - name: ansible.windows
  - name: community.general
  - name: community.windows


# Add the required logging role
- name: sandbox-logging
  src: https://github.com/cyberrangecz/ansible-role-sandbox-logging.git
  scm: git
  version: v1.0.0
